// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: pkg/protocol/backimage.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hello struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientVersion   string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	ProtocolVersion uint32 `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	SessionId       string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AuthToken       string `protobuf:"bytes,4,opt,name=auth_token,json=authToken,proto3" json:"auth_token,omitempty"`
}

func (x *Hello) Reset() {
	*x = Hello{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{0}
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Hello) GetAuthToken() string {
	if x != nil {
		return x.AuthToken
	}
	return ""
}

type HelloAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerVersion       string   `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	ProtocolVersion     uint32   `protobuf:"varint,2,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	MaxBytes            uint64   `protobuf:"varint,3,opt,name=max_bytes,json=maxBytes,proto3" json:"max_bytes,omitempty"`
	AllowedRepoPrefixes []string `protobuf:"bytes,4,rep,name=allowed_repo_prefixes,json=allowedRepoPrefixes,proto3" json:"allowed_repo_prefixes,omitempty"`
	Resumable           bool     `protobuf:"varint,5,opt,name=resumable,proto3" json:"resumable,omitempty"`
	KnownBlobDigests    []string `protobuf:"bytes,6,rep,name=known_blob_digests,json=knownBlobDigests,proto3" json:"known_blob_digests,omitempty"`
	// streaming reports whether the server runs the whole pipeline itself
	// (protocol v2): the client only sends the raw archive stream.
	Streaming bool `protobuf:"varint,7,opt,name=streaming,proto3" json:"streaming,omitempty"`
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{1}
}

func (x *HelloAck) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HelloAck) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *HelloAck) GetMaxBytes() uint64 {
	if x != nil {
		return x.MaxBytes
	}
	return 0
}

func (x *HelloAck) GetAllowedRepoPrefixes() []string {
	if x != nil {
		return x.AllowedRepoPrefixes
	}
	return nil
}

func (x *HelloAck) GetResumable() bool {
	if x != nil {
		return x.Resumable
	}
	return false
}

func (x *HelloAck) GetKnownBlobDigests() []string {
	if x != nil {
		return x.KnownBlobDigests
	}
	return nil
}

func (x *HelloAck) GetStreaming() bool {
	if x != nil {
		return x.Streaming
	}
	return false
}

type BackupStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference        string      `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	ManifestJson     []byte      `protobuf:"bytes,2,opt,name=manifest_json,json=manifestJson,proto3" json:"manifest_json,omitempty"`
	LayerCount       uint32      `protobuf:"varint,3,opt,name=layer_count,json=layerCount,proto3" json:"layer_count,omitempty"`
	EstimatedBytes   uint64      `protobuf:"varint,4,opt,name=estimated_bytes,json=estimatedBytes,proto3" json:"estimated_bytes,omitempty"`
	Platforms        []*Platform `protobuf:"bytes,5,rep,name=platforms,proto3" json:"platforms,omitempty"`
	SelfextractAmd64 []byte      `protobuf:"bytes,6,opt,name=selfextract_amd64,json=selfextractAmd64,proto3" json:"selfextract_amd64,omitempty"`
	SelfextractArm64 []byte      `protobuf:"bytes,7,opt,name=selfextract_arm64,json=selfextractArm64,proto3" json:"selfextract_arm64,omitempty"`
	MetadataLayer    []byte      `protobuf:"bytes,8,opt,name=metadata_layer,json=metadataLayer,proto3" json:"metadata_layer,omitempty"`
}

func (x *BackupStart) Reset() {
	*x = BackupStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupStart) ProtoMessage() {}

func (x *BackupStart) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupStart.ProtoReflect.Descriptor instead.
func (*BackupStart) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{2}
}

func (x *BackupStart) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *BackupStart) GetManifestJson() []byte {
	if x != nil {
		return x.ManifestJson
	}
	return nil
}

func (x *BackupStart) GetLayerCount() uint32 {
	if x != nil {
		return x.LayerCount
	}
	return 0
}

func (x *BackupStart) GetEstimatedBytes() uint64 {
	if x != nil {
		return x.EstimatedBytes
	}
	return 0
}

func (x *BackupStart) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *BackupStart) GetSelfextractAmd64() []byte {
	if x != nil {
		return x.SelfextractAmd64
	}
	return nil
}

func (x *BackupStart) GetSelfextractArm64() []byte {
	if x != nil {
		return x.SelfextractArm64
	}
	return nil
}

func (x *BackupStart) GetMetadataLayer() []byte {
	if x != nil {
		return x.MetadataLayer
	}
	return nil
}

type Platform struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Os           string `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Architecture string `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
}

func (x *Platform) Reset() {
	*x = Platform{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Platform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Platform) ProtoMessage() {}

func (x *Platform) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Platform.ProtoReflect.Descriptor instead.
func (*Platform) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{3}
}

func (x *Platform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Platform) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

type LayerStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index     uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Size      uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Sha256    string `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	DiffId    string `protobuf:"bytes,4,opt,name=diff_id,json=diffId,proto3" json:"diff_id,omitempty"`
	MediaType string `protobuf:"bytes,5,opt,name=media_type,json=mediaType,proto3" json:"media_type,omitempty"`
}

func (x *LayerStart) Reset() {
	*x = LayerStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayerStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerStart) ProtoMessage() {}

func (x *LayerStart) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerStart.ProtoReflect.Descriptor instead.
func (*LayerStart) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{4}
}

func (x *LayerStart) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LayerStart) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LayerStart) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *LayerStart) GetDiffId() string {
	if x != nil {
		return x.DiffId
	}
	return ""
}

func (x *LayerStart) GetMediaType() string {
	if x != nil {
		return x.MediaType
	}
	return ""
}

type LayerEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index  uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Digest string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
}

func (x *LayerEnd) Reset() {
	*x = LayerEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayerEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerEnd) ProtoMessage() {}

func (x *LayerEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerEnd.ProtoReflect.Descriptor instead.
func (*LayerEnd) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{5}
}

func (x *LayerEnd) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LayerEnd) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

type Token struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value         string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	ExpiresAtUnix int64    `protobuf:"varint,2,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	Repository    string   `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	Actions       []string `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	Anonymous     bool     `protobuf:"varint,5,opt,name=anonymous,proto3" json:"anonymous,omitempty"`
}

func (x *Token) Reset() {
	*x = Token{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Token) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Token) ProtoMessage() {}

func (x *Token) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Token.ProtoReflect.Descriptor instead.
func (*Token) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{6}
}

func (x *Token) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Token) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *Token) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *Token) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *Token) GetAnonymous() bool {
	if x != nil {
		return x.Anonymous
	}
	return false
}

type TokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repository string   `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	Actions    []string `protobuf:"bytes,2,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *TokenRequest) Reset() {
	*x = TokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenRequest) ProtoMessage() {}

func (x *TokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenRequest.ProtoReflect.Descriptor instead.
func (*TokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{7}
}

func (x *TokenRequest) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *TokenRequest) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

type Progress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Layer    uint32 `protobuf:"varint,1,opt,name=layer,proto3" json:"layer,omitempty"`
	Uploaded uint64 `protobuf:"varint,2,opt,name=uploaded,proto3" json:"uploaded,omitempty"`
	Skipped  bool   `protobuf:"varint,3,opt,name=skipped,proto3" json:"skipped,omitempty"`
}

func (x *Progress) Reset() {
	*x = Progress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Progress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Progress) ProtoMessage() {}

func (x *Progress) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Progress.ProtoReflect.Descriptor instead.
func (*Progress) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{8}
}

func (x *Progress) GetLayer() uint32 {
	if x != nil {
		return x.Layer
	}
	return 0
}

func (x *Progress) GetUploaded() uint64 {
	if x != nil {
		return x.Uploaded
	}
	return 0
}

func (x *Progress) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

type BackupEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Digest        string `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	BytesUploaded uint64 `protobuf:"varint,2,opt,name=bytes_uploaded,json=bytesUploaded,proto3" json:"bytes_uploaded,omitempty"`
	BlobsSkipped  uint32 `protobuf:"varint,3,opt,name=blobs_skipped,json=blobsSkipped,proto3" json:"blobs_skipped,omitempty"`
	// Fields below are only populated by the streaming protocol (v2), where the
	// server owns the pipeline and therefore owns these counters.
	RawBytes    uint64 `protobuf:"varint,4,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
	StoredBytes uint64 `protobuf:"varint,5,opt,name=stored_bytes,json=storedBytes,proto3" json:"stored_bytes,omitempty"`
	Layers      uint32 `protobuf:"varint,6,opt,name=layers,proto3" json:"layers,omitempty"`
	Chunks      uint32 `protobuf:"varint,7,opt,name=chunks,proto3" json:"chunks,omitempty"`
	Files       int64  `protobuf:"varint,8,opt,name=files,proto3" json:"files,omitempty"`
}

func (x *BackupEnd) Reset() {
	*x = BackupEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupEnd) ProtoMessage() {}

func (x *BackupEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupEnd.ProtoReflect.Descriptor instead.
func (*BackupEnd) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{9}
}

func (x *BackupEnd) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *BackupEnd) GetBytesUploaded() uint64 {
	if x != nil {
		return x.BytesUploaded
	}
	return 0
}

func (x *BackupEnd) GetBlobsSkipped() uint32 {
	if x != nil {
		return x.BlobsSkipped
	}
	return 0
}

func (x *BackupEnd) GetRawBytes() uint64 {
	if x != nil {
		return x.RawBytes
	}
	return 0
}

func (x *BackupEnd) GetStoredBytes() uint64 {
	if x != nil {
		return x.StoredBytes
	}
	return 0
}

func (x *BackupEnd) GetLayers() uint32 {
	if x != nil {
		return x.Layers
	}
	return 0
}

func (x *BackupEnd) GetChunks() uint32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

func (x *BackupEnd) GetFiles() int64 {
	if x != nil {
		return x.Files
	}
	return 0
}

// StreamStart opens a protocol v2 session: the client only ships the raw tar
// stream, the server performs chunking, compression, encryption, layer
// assembly and the registry push.
type StreamStart struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reference      string            `protobuf:"bytes,1,opt,name=reference,proto3" json:"reference,omitempty"`
	ToolVersion    string            `protobuf:"bytes,2,opt,name=tool_version,json=toolVersion,proto3" json:"tool_version,omitempty"`
	Created        string            `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"` // RFC3339, empty = server wall clock
	Archive        *ArchiveConfig    `protobuf:"bytes,4,opt,name=archive,proto3" json:"archive,omitempty"`
	Encryption     *EncryptionConfig `protobuf:"bytes,5,opt,name=encryption,proto3" json:"encryption,omitempty"`
	Platforms      []*Platform       `protobuf:"bytes,6,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Runnable       bool              `protobuf:"varint,7,opt,name=runnable,proto3" json:"runnable,omitempty"`
	EstimatedBytes uint64            `protobuf:"varint,8,opt,name=estimated_bytes,json=estimatedBytes,proto3" json:"estimated_bytes,omitempty"`
	EstimatedFiles int64             `protobuf:"varint,9,opt,name=estimated_files,json=estimatedFiles,proto3" json:"estimated_files,omitempty"`
	Sources        []string          `protobuf:"bytes,10,rep,name=sources,proto3" json:"sources,omitempty"` // empty with --no-metadata
	Host           *HostInfo         `protobuf:"bytes,11,opt,name=host,proto3" json:"host,omitempty"`
	Dedup          bool              `protobuf:"varint,12,opt,name=dedup,proto3" json:"dedup,omitempty"`
	Cdc            *CDCParams        `protobuf:"bytes,13,opt,name=cdc,proto3" json:"cdc,omitempty"`
	MaxLayerBytes  uint64            `protobuf:"varint,14,opt,name=max_layer_bytes,json=maxLayerBytes,proto3" json:"max_layer_bytes,omitempty"`
}

func (x *StreamStart) Reset() {
	*x = StreamStart{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamStart) ProtoMessage() {}

func (x *StreamStart) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamStart.ProtoReflect.Descriptor instead.
func (*StreamStart) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{10}
}

func (x *StreamStart) GetReference() string {
	if x != nil {
		return x.Reference
	}
	return ""
}

func (x *StreamStart) GetToolVersion() string {
	if x != nil {
		return x.ToolVersion
	}
	return ""
}

func (x *StreamStart) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *StreamStart) GetArchive() *ArchiveConfig {
	if x != nil {
		return x.Archive
	}
	return nil
}

func (x *StreamStart) GetEncryption() *EncryptionConfig {
	if x != nil {
		return x.Encryption
	}
	return nil
}

func (x *StreamStart) GetPlatforms() []*Platform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *StreamStart) GetRunnable() bool {
	if x != nil {
		return x.Runnable
	}
	return false
}

func (x *StreamStart) GetEstimatedBytes() uint64 {
	if x != nil {
		return x.EstimatedBytes
	}
	return 0
}

func (x *StreamStart) GetEstimatedFiles() int64 {
	if x != nil {
		return x.EstimatedFiles
	}
	return 0
}

func (x *StreamStart) GetSources() []string {
	if x != nil {
		return x.Sources
	}
	return nil
}

func (x *StreamStart) GetHost() *HostInfo {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *StreamStart) GetDedup() bool {
	if x != nil {
		return x.Dedup
	}
	return false
}

func (x *StreamStart) GetCdc() *CDCParams {
	if x != nil {
		return x.Cdc
	}
	return nil
}

func (x *StreamStart) GetMaxLayerBytes() uint64 {
	if x != nil {
		return x.MaxLayerBytes
	}
	return 0
}

type ArchiveConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Compression string `protobuf:"bytes,1,opt,name=compression,proto3" json:"compression,omitempty"`
	Level       int32  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
}

func (x *ArchiveConfig) Reset() {
	*x = ArchiveConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveConfig) ProtoMessage() {}

func (x *ArchiveConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveConfig.ProtoReflect.Descriptor instead.
func (*ArchiveConfig) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{11}
}

func (x *ArchiveConfig) GetCompression() string {
	if x != nil {
		return x.Compression
	}
	return ""
}

func (x *ArchiveConfig) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type CDCParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Min        uint64 `protobuf:"varint,1,opt,name=min,proto3" json:"min,omitempty"`
	Avg        uint64 `protobuf:"varint,2,opt,name=avg,proto3" json:"avg,omitempty"`
	Max        uint64 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Polynomial uint64 `protobuf:"varint,4,opt,name=polynomial,proto3" json:"polynomial,omitempty"`
}

func (x *CDCParams) Reset() {
	*x = CDCParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CDCParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CDCParams) ProtoMessage() {}

func (x *CDCParams) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CDCParams.ProtoReflect.Descriptor instead.
func (*CDCParams) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{12}
}

func (x *CDCParams) GetMin() uint64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *CDCParams) GetAvg() uint64 {
	if x != nil {
		return x.Avg
	}
	return 0
}

func (x *CDCParams) GetMax() uint64 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *CDCParams) GetPolynomial() uint64 {
	if x != nil {
		return x.Polynomial
	}
	return 0
}

type HostInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hostname string `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os       string `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch     string `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
}

func (x *HostInfo) Reset() {
	*x = HostInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HostInfo) ProtoMessage() {}

func (x *HostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HostInfo.ProtoReflect.Descriptor instead.
func (*HostInfo) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{13}
}

func (x *HostInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *HostInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *HostInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// EncryptionConfig carries the data encryption key to the server, which needs
// it to seal chunks and the file index. The passphrase never leaves the
// client: key_files holds the age-wrapped copies stored inside the image.
type EncryptionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enabled        bool              `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Dek            []byte            `protobuf:"bytes,2,opt,name=dek,proto3" json:"dek,omitempty"`
	NonceMode      string            `protobuf:"bytes,3,opt,name=nonce_mode,json=nonceMode,proto3" json:"nonce_mode,omitempty"` // random|convergent
	KeyFiles       map[string][]byte `protobuf:"bytes,4,rep,name=key_files,json=keyFiles,proto3" json:"key_files,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Recipients     []string          `protobuf:"bytes,5,rep,name=recipients,proto3" json:"recipients,omitempty"`
	KeyFingerprint string            `protobuf:"bytes,6,opt,name=key_fingerprint,json=keyFingerprint,proto3" json:"key_fingerprint,omitempty"`
	// nonce_key is only used by the convergent mode; it must be the same key
	// stored in the age key files so that later backups deduplicate.
	NonceKey []byte `protobuf:"bytes,7,opt,name=nonce_key,json=nonceKey,proto3" json:"nonce_key,omitempty"`
}

func (x *EncryptionConfig) Reset() {
	*x = EncryptionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EncryptionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptionConfig) ProtoMessage() {}

func (x *EncryptionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptionConfig.ProtoReflect.Descriptor instead.
func (*EncryptionConfig) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{14}
}

func (x *EncryptionConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *EncryptionConfig) GetDek() []byte {
	if x != nil {
		return x.Dek
	}
	return nil
}

func (x *EncryptionConfig) GetNonceMode() string {
	if x != nil {
		return x.NonceMode
	}
	return ""
}

func (x *EncryptionConfig) GetKeyFiles() map[string][]byte {
	if x != nil {
		return x.KeyFiles
	}
	return nil
}

func (x *EncryptionConfig) GetRecipients() []string {
	if x != nil {
		return x.Recipients
	}
	return nil
}

func (x *EncryptionConfig) GetKeyFingerprint() string {
	if x != nil {
		return x.KeyFingerprint
	}
	return ""
}

func (x *EncryptionConfig) GetNonceKey() []byte {
	if x != nil {
		return x.NonceKey
	}
	return nil
}

type StreamAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready        bool          `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	TokenRequest *TokenRequest `protobuf:"bytes,2,opt,name=token_request,json=tokenRequest,proto3" json:"token_request,omitempty"`
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{15}
}

func (x *StreamAck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *StreamAck) GetTokenRequest() *TokenRequest {
	if x != nil {
		return x.TokenRequest
	}
	return nil
}

type StreamEnd struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RawBytes uint64 `protobuf:"varint,1,opt,name=raw_bytes,json=rawBytes,proto3" json:"raw_bytes,omitempty"`
}

func (x *StreamEnd) Reset() {
	*x = StreamEnd{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamEnd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEnd) ProtoMessage() {}

func (x *StreamEnd) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEnd.ProtoReflect.Descriptor instead.
func (*StreamEnd) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{16}
}

func (x *StreamEnd) GetRawBytes() uint64 {
	if x != nil {
		return x.RawBytes
	}
	return 0
}

type StreamProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Stage         string `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"` // receiving|archiving|compressing|encrypting|pushing|publishing
	ReceivedBytes uint64 `protobuf:"varint,2,opt,name=received_bytes,json=receivedBytes,proto3" json:"received_bytes,omitempty"`
	StoredBytes   uint64 `protobuf:"varint,3,opt,name=stored_bytes,json=storedBytes,proto3" json:"stored_bytes,omitempty"`
	UploadedBytes uint64 `protobuf:"varint,4,opt,name=uploaded_bytes,json=uploadedBytes,proto3" json:"uploaded_bytes,omitempty"`
	Layers        uint32 `protobuf:"varint,5,opt,name=layers,proto3" json:"layers,omitempty"`
	LayersSkipped uint32 `protobuf:"varint,6,opt,name=layers_skipped,json=layersSkipped,proto3" json:"layers_skipped,omitempty"`
	Chunks        uint32 `protobuf:"varint,7,opt,name=chunks,proto3" json:"chunks,omitempty"`
}

func (x *StreamProgress) Reset() {
	*x = StreamProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamProgress) ProtoMessage() {}

func (x *StreamProgress) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamProgress.ProtoReflect.Descriptor instead.
func (*StreamProgress) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{17}
}

func (x *StreamProgress) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *StreamProgress) GetReceivedBytes() uint64 {
	if x != nil {
		return x.ReceivedBytes
	}
	return 0
}

func (x *StreamProgress) GetStoredBytes() uint64 {
	if x != nil {
		return x.StoredBytes
	}
	return 0
}

func (x *StreamProgress) GetUploadedBytes() uint64 {
	if x != nil {
		return x.UploadedBytes
	}
	return 0
}

func (x *StreamProgress) GetLayers() uint32 {
	if x != nil {
		return x.Layers
	}
	return 0
}

func (x *StreamProgress) GetLayersSkipped() uint32 {
	if x != nil {
		return x.LayersSkipped
	}
	return 0
}

func (x *StreamProgress) GetChunks() uint32 {
	if x != nil {
		return x.Chunks
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind    uint32 `protobuf:"varint,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Hint    string `protobuf:"bytes,3,opt,name=hint,proto3" json:"hint,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{18}
}

func (x *Error) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetHint() string {
	if x != nil {
		return x.Hint
	}
	return ""
}

type ClientMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ClientMessage_Hello
	//	*ClientMessage_BackupStart
	//	*ClientMessage_LayerStart
	//	*ClientMessage_LayerEnd
	//	*ClientMessage_Token
	//	*ClientMessage_Error
	//	*ClientMessage_Cancel
	//	*ClientMessage_StreamStart
	//	*ClientMessage_StreamEnd
	Msg isClientMessage_Msg `protobuf_oneof:"msg"`
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{19}
}

func (m *ClientMessage) GetMsg() isClientMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ClientMessage) GetHello() *Hello {
	if x, ok := x.GetMsg().(*ClientMessage_Hello); ok {
		return x.Hello
	}
	return nil
}

func (x *ClientMessage) GetBackupStart() *BackupStart {
	if x, ok := x.GetMsg().(*ClientMessage_BackupStart); ok {
		return x.BackupStart
	}
	return nil
}

func (x *ClientMessage) GetLayerStart() *LayerStart {
	if x, ok := x.GetMsg().(*ClientMessage_LayerStart); ok {
		return x.LayerStart
	}
	return nil
}

func (x *ClientMessage) GetLayerEnd() *LayerEnd {
	if x, ok := x.GetMsg().(*ClientMessage_LayerEnd); ok {
		return x.LayerEnd
	}
	return nil
}

func (x *ClientMessage) GetToken() *Token {
	if x, ok := x.GetMsg().(*ClientMessage_Token); ok {
		return x.Token
	}
	return nil
}

func (x *ClientMessage) GetError() *Error {
	if x, ok := x.GetMsg().(*ClientMessage_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ClientMessage) GetCancel() *Cancel {
	if x, ok := x.GetMsg().(*ClientMessage_Cancel); ok {
		return x.Cancel
	}
	return nil
}

func (x *ClientMessage) GetStreamStart() *StreamStart {
	if x, ok := x.GetMsg().(*ClientMessage_StreamStart); ok {
		return x.StreamStart
	}
	return nil
}

func (x *ClientMessage) GetStreamEnd() *StreamEnd {
	if x, ok := x.GetMsg().(*ClientMessage_StreamEnd); ok {
		return x.StreamEnd
	}
	return nil
}

type isClientMessage_Msg interface {
	isClientMessage_Msg()
}

type ClientMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientMessage_BackupStart struct {
	BackupStart *BackupStart `protobuf:"bytes,2,opt,name=backup_start,json=backupStart,proto3,oneof"`
}

type ClientMessage_LayerStart struct {
	LayerStart *LayerStart `protobuf:"bytes,3,opt,name=layer_start,json=layerStart,proto3,oneof"`
}

type ClientMessage_LayerEnd struct {
	LayerEnd *LayerEnd `protobuf:"bytes,4,opt,name=layer_end,json=layerEnd,proto3,oneof"`
}

type ClientMessage_Token struct {
	Token *Token `protobuf:"bytes,5,opt,name=token,proto3,oneof"`
}

type ClientMessage_Error struct {
	Error *Error `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type ClientMessage_Cancel struct {
	Cancel *Cancel `protobuf:"bytes,7,opt,name=cancel,proto3,oneof"`
}

type ClientMessage_StreamStart struct {
	StreamStart *StreamStart `protobuf:"bytes,8,opt,name=stream_start,json=streamStart,proto3,oneof"`
}

type ClientMessage_StreamEnd struct {
	StreamEnd *StreamEnd `protobuf:"bytes,9,opt,name=stream_end,json=streamEnd,proto3,oneof"`
}

func (*ClientMessage_Hello) isClientMessage_Msg() {}

func (*ClientMessage_BackupStart) isClientMessage_Msg() {}

func (*ClientMessage_LayerStart) isClientMessage_Msg() {}

func (*ClientMessage_LayerEnd) isClientMessage_Msg() {}

func (*ClientMessage_Token) isClientMessage_Msg() {}

func (*ClientMessage_Error) isClientMessage_Msg() {}

func (*ClientMessage_Cancel) isClientMessage_Msg() {}

func (*ClientMessage_StreamStart) isClientMessage_Msg() {}

func (*ClientMessage_StreamEnd) isClientMessage_Msg() {}

type ServerMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Msg:
	//
	//	*ServerMessage_HelloAck
	//	*ServerMessage_TokenRequest
	//	*ServerMessage_Progress
	//	*ServerMessage_BackupEnd
	//	*ServerMessage_Error
	//	*ServerMessage_LayerAck
	//	*ServerMessage_BackupAck
	//	*ServerMessage_StreamAck
	//	*ServerMessage_StreamProgress
	Msg isServerMessage_Msg `protobuf_oneof:"msg"`
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{20}
}

func (m *ServerMessage) GetMsg() isServerMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (x *ServerMessage) GetHelloAck() *HelloAck {
	if x, ok := x.GetMsg().(*ServerMessage_HelloAck); ok {
		return x.HelloAck
	}
	return nil
}

func (x *ServerMessage) GetTokenRequest() *TokenRequest {
	if x, ok := x.GetMsg().(*ServerMessage_TokenRequest); ok {
		return x.TokenRequest
	}
	return nil
}

func (x *ServerMessage) GetProgress() *Progress {
	if x, ok := x.GetMsg().(*ServerMessage_Progress); ok {
		return x.Progress
	}
	return nil
}

func (x *ServerMessage) GetBackupEnd() *BackupEnd {
	if x, ok := x.GetMsg().(*ServerMessage_BackupEnd); ok {
		return x.BackupEnd
	}
	return nil
}

func (x *ServerMessage) GetError() *Error {
	if x, ok := x.GetMsg().(*ServerMessage_Error); ok {
		return x.Error
	}
	return nil
}

func (x *ServerMessage) GetLayerAck() *LayerAck {
	if x, ok := x.GetMsg().(*ServerMessage_LayerAck); ok {
		return x.LayerAck
	}
	return nil
}

func (x *ServerMessage) GetBackupAck() *BackupAck {
	if x, ok := x.GetMsg().(*ServerMessage_BackupAck); ok {
		return x.BackupAck
	}
	return nil
}

func (x *ServerMessage) GetStreamAck() *StreamAck {
	if x, ok := x.GetMsg().(*ServerMessage_StreamAck); ok {
		return x.StreamAck
	}
	return nil
}

func (x *ServerMessage) GetStreamProgress() *StreamProgress {
	if x, ok := x.GetMsg().(*ServerMessage_StreamProgress); ok {
		return x.StreamProgress
	}
	return nil
}

type isServerMessage_Msg interface {
	isServerMessage_Msg()
}

type ServerMessage_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,1,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type ServerMessage_TokenRequest struct {
	TokenRequest *TokenRequest `protobuf:"bytes,2,opt,name=token_request,json=tokenRequest,proto3,oneof"`
}

type ServerMessage_Progress struct {
	Progress *Progress `protobuf:"bytes,3,opt,name=progress,proto3,oneof"`
}

type ServerMessage_BackupEnd struct {
	BackupEnd *BackupEnd `protobuf:"bytes,4,opt,name=backup_end,json=backupEnd,proto3,oneof"`
}

type ServerMessage_Error struct {
	Error *Error `protobuf:"bytes,5,opt,name=error,proto3,oneof"`
}

type ServerMessage_LayerAck struct {
	LayerAck *LayerAck `protobuf:"bytes,6,opt,name=layer_ack,json=layerAck,proto3,oneof"`
}

type ServerMessage_BackupAck struct {
	BackupAck *BackupAck `protobuf:"bytes,7,opt,name=backup_ack,json=backupAck,proto3,oneof"`
}

type ServerMessage_StreamAck struct {
	StreamAck *StreamAck `protobuf:"bytes,8,opt,name=stream_ack,json=streamAck,proto3,oneof"`
}

type ServerMessage_StreamProgress struct {
	StreamProgress *StreamProgress `protobuf:"bytes,9,opt,name=stream_progress,json=streamProgress,proto3,oneof"`
}

func (*ServerMessage_HelloAck) isServerMessage_Msg() {}

func (*ServerMessage_TokenRequest) isServerMessage_Msg() {}

func (*ServerMessage_Progress) isServerMessage_Msg() {}

func (*ServerMessage_BackupEnd) isServerMessage_Msg() {}

func (*ServerMessage_Error) isServerMessage_Msg() {}

func (*ServerMessage_LayerAck) isServerMessage_Msg() {}

func (*ServerMessage_BackupAck) isServerMessage_Msg() {}

func (*ServerMessage_StreamAck) isServerMessage_Msg() {}

func (*ServerMessage_StreamProgress) isServerMessage_Msg() {}

type BackupAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ready        bool          `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	TokenRequest *TokenRequest `protobuf:"bytes,2,opt,name=token_request,json=tokenRequest,proto3" json:"token_request,omitempty"`
}

func (x *BackupAck) Reset() {
	*x = BackupAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BackupAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupAck) ProtoMessage() {}

func (x *BackupAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupAck.ProtoReflect.Descriptor instead.
func (*BackupAck) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{21}
}

func (x *BackupAck) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *BackupAck) GetTokenRequest() *TokenRequest {
	if x != nil {
		return x.TokenRequest
	}
	return nil
}

type LayerAck struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Index   uint32 `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Skipped bool   `protobuf:"varint,2,opt,name=skipped,proto3" json:"skipped,omitempty"`
}

func (x *LayerAck) Reset() {
	*x = LayerAck{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LayerAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LayerAck) ProtoMessage() {}

func (x *LayerAck) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LayerAck.ProtoReflect.Descriptor instead.
func (*LayerAck) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{22}
}

func (x *LayerAck) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *LayerAck) GetSkipped() bool {
	if x != nil {
		return x.Skipped
	}
	return false
}

type Cancel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reason string `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
}

func (x *Cancel) Reset() {
	*x = Cancel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_protocol_backimage_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Cancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cancel) ProtoMessage() {}

func (x *Cancel) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_protocol_backimage_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cancel.ProtoReflect.Descriptor instead.
func (*Cancel) Descriptor() ([]byte, []int) {
	return file_pkg_protocol_backimage_proto_rawDescGZIP(), []int{23}
}

func (x *Cancel) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_pkg_protocol_backimage_proto protoreflect.FileDescriptor

var file_pkg_protocol_backimage_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c,
	0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x97, 0x01, 0x0a,
	0x05, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a,
	0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x5f,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x75, 0x74,
	0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x97, 0x02, 0x0a, 0x08, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x41, 0x63, 0x6b, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x79, 0x74,
	0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x42, 0x79, 0x74,
	0x65, 0x73, 0x12, 0x32, 0x0a, 0x15, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x5f, 0x72, 0x65,
	0x70, 0x6f, 0x5f, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x13, 0x61, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x52, 0x65, 0x70, 0x6f, 0x50, 0x72,
	0x65, 0x66, 0x69, 0x78, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6d, 0x61,
	0x62, 0x6c, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x72, 0x65, 0x73, 0x75, 0x6d,
	0x61, 0x62, 0x6c, 0x65, 0x12, 0x2c, 0x0a, 0x12, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x5f, 0x62, 0x6c,
	0x6f, 0x62, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x10, 0x6b, 0x6e, 0x6f, 0x77, 0x6e, 0x42, 0x6c, 0x6f, 0x62, 0x44, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x69, 0x6e, 0x67,
	0x22, 0xd1, 0x02, 0x0a, 0x0b, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x23,
	0x0a, 0x0d, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x5f, 0x6a, 0x73, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c, 0x6d, 0x61, 0x6e, 0x69, 0x66, 0x65, 0x73, 0x74, 0x4a,
	0x73, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x65,
	0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x34, 0x0a,
	0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f,
	0x72, 0x6d, 0x73, 0x12, 0x2b, 0x0a, 0x11, 0x73, 0x65, 0x6c, 0x66, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x5f, 0x61, 0x6d, 0x64, 0x36, 0x34, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10,
	0x73, 0x65, 0x6c, 0x66, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x6d, 0x64, 0x36, 0x34,
	0x12, 0x2b, 0x0a, 0x11, 0x73, 0x65, 0x6c, 0x66, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f,
	0x61, 0x72, 0x6d, 0x36, 0x34, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x10, 0x73, 0x65, 0x6c,
	0x66, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x41, 0x72, 0x6d, 0x36, 0x34, 0x12, 0x25, 0x0a,
	0x0e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x4c,
	0x61, 0x79, 0x65, 0x72, 0x22, 0x3e, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73,
	0x12, 0x22, 0x0a, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x72, 0x63, 0x68, 0x69, 0x74, 0x65, 0x63,
	0x74, 0x75, 0x72, 0x65, 0x22, 0x86, 0x01, 0x0a, 0x0a, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x68, 0x61, 0x32, 0x35, 0x36, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x68, 0x61, 0x32, 0x35, 0x36, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x69, 0x66, 0x66, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x66, 0x66, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x6d, 0x65, 0x64, 0x69, 0x61, 0x54, 0x79, 0x70, 0x65, 0x22, 0x38, 0x0a,
	0x08, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64,
	0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x22, 0x9d, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x65, 0x73, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0d, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x12,
	0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x6e, 0x6f,
	0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x61, 0x6e,
	0x6f, 0x6e, 0x79, 0x6d, 0x6f, 0x75, 0x73, 0x22, 0x48, 0x0a, 0x0c, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x70,
	0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x22, 0x56, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x07, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x22, 0xf5, 0x01, 0x0a, 0x09, 0x42, 0x61,
	0x63, 0x6b, 0x75, 0x70, 0x45, 0x6e, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x25, 0x0a, 0x0e, 0x62, 0x79, 0x74, 0x65, 0x73, 0x5f, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x62, 0x79, 0x74, 0x65, 0x73, 0x55, 0x70,
	0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x6c, 0x6f, 0x62, 0x73, 0x5f,
	0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x62,
	0x6c, 0x6f, 0x62, 0x73, 0x53, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x61, 0x77, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x6f, 0x72,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66,
	0x69, 0x6c, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x22, 0xb2, 0x04, 0x0a, 0x0b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12,
	0x21, 0x0a, 0x0c, 0x74, 0x6f, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x74, 0x6f, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x35, 0x0a, 0x07,
	0x61, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e,
	0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x72, 0x63,
	0x68, 0x69, 0x76, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x07, 0x61, 0x72, 0x63, 0x68,
	0x69, 0x76, 0x65, 0x12, 0x3e, 0x0a, 0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0a, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73,
	0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x09,
	0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x72, 0x75, 0x6e,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x72, 0x75, 0x6e,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x27, 0x0a, 0x0f, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e,
	0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x27,
	0x0a, 0x0f, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x65, 0x73, 0x74, 0x69, 0x6d, 0x61, 0x74,
	0x65, 0x64, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x73, 0x12, 0x2a, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x64, 0x65, 0x64, 0x75, 0x70, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x64, 0x65,
	0x64, 0x75, 0x70, 0x12, 0x29, 0x0a, 0x03, 0x63, 0x64, 0x63, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x43, 0x44, 0x43, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x03, 0x63, 0x64, 0x63, 0x12, 0x26,
	0x0a, 0x0f, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6d, 0x61, 0x78, 0x4c, 0x61, 0x79, 0x65,
	0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0x47, 0x0a, 0x0d, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76,
	0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76,
	0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x22,
	0x61, 0x0a, 0x09, 0x43, 0x44, 0x43, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x76, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x61, 0x76, 0x67,
	0x12, 0x10, 0x0a, 0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6d,
	0x61, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x6c, 0x79, 0x6e, 0x6f, 0x6d, 0x69, 0x61, 0x6c,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x70, 0x6f, 0x6c, 0x79, 0x6e, 0x6f, 0x6d, 0x69,
	0x61, 0x6c, 0x22, 0x4a, 0x0a, 0x08, 0x48, 0x6f, 0x73, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72,
	0x63, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x22, 0xcb,
	0x02, 0x0a, 0x10, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x64, 0x65, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x64, 0x65, 0x6b, 0x12,
	0x1d, 0x0a, 0x0a, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x49,
	0x0a, 0x09, 0x6b, 0x65, 0x79, 0x5f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x2c, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x2e, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52,
	0x08, 0x6b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x72, 0x65, 0x63,
	0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x72,
	0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x6b, 0x65, 0x79,
	0x5f, 0x66, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x6b, 0x65, 0x79, 0x46, 0x69, 0x6e, 0x67, 0x65, 0x72, 0x70, 0x72, 0x69,
	0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x4b, 0x65, 0x79, 0x1a,
	0x3b, 0x0a, 0x0d, 0x4b, 0x65, 0x79, 0x46, 0x69, 0x6c, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x62, 0x0a, 0x09,
	0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12,
	0x3f, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x28, 0x0a, 0x09, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x72, 0x61, 0x77, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x08, 0x72, 0x61, 0x77, 0x42, 0x79, 0x74, 0x65, 0x73, 0x22, 0xee, 0x01, 0x0a, 0x0e, 0x53,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74,
	0x61, 0x67, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74,
	0x6f, 0x72, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x0b, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x25, 0x0a,
	0x0e, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x65, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x12, 0x25, 0x0a, 0x0e,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x5f, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0d, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x53, 0x6b, 0x69, 0x70,
	0x70, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x06, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x73, 0x22, 0x49, 0x0a, 0x05, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x69, 0x6e, 0x74, 0x22, 0xfb, 0x03, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05,
	0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x3e, 0x0a, 0x0c, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x61,
	0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75,
	0x70, 0x53, 0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x3b, 0x0a, 0x0b, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x72, 0x74, 0x12, 0x35, 0x0a, 0x09, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x65, 0x6e, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x48, 0x00, 0x52,
	0x08, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x45, 0x6e, 0x64, 0x12, 0x2b, 0x0a, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x48, 0x00, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x2e, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x18, 0x07, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x48, 0x00, 0x52, 0x06, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x12, 0x3e, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x12, 0x38, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x65, 0x6e,
	0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d,
	0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64,
	0x48, 0x00, 0x52, 0x09, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x45, 0x6e, 0x64, 0x42, 0x05, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0xa1, 0x04, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x35, 0x0a, 0x09, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x5f,
	0x61, 0x63, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x08, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x41, 0x63, 0x6b, 0x12, 0x41, 0x0a,
	0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x48, 0x00, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x34, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48, 0x00, 0x52, 0x08, 0x70, 0x72,
	0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x38, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x5f, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x63,
	0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70,
	0x45, 0x6e, 0x64, 0x48, 0x00, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x45, 0x6e, 0x64,
	0x12, 0x2b, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x35, 0x0a,
	0x09, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x08, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x41, 0x63, 0x6b, 0x12, 0x38, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x5f, 0x61,
	0x63, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69,
	0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x63,
	0x6b, 0x48, 0x00, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x41, 0x63, 0x6b, 0x12, 0x38,
	0x0a, 0x0a, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f, 0x61, 0x63, 0x6b, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x09, 0x73,
	0x74, 0x72, 0x65, 0x61, 0x6d, 0x41, 0x63, 0x6b, 0x12, 0x47, 0x0a, 0x0f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x48,
	0x00, 0x52, 0x0e, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x05, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x62, 0x0a, 0x09, 0x42, 0x61, 0x63, 0x6b,
	0x75, 0x70, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x61, 0x64, 0x79, 0x12, 0x3f, 0x0a, 0x0d, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x08,
	0x4c, 0x61, 0x79, 0x65, 0x72, 0x41, 0x63, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65,
	0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x73, 0x6b, 0x69, 0x70, 0x70, 0x65, 0x64, 0x22, 0x20, 0x0a, 0x06, 0x43, 0x61, 0x6e, 0x63,
	0x65, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x70, 0x72, 0x69, 0x6e,
	0x74, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_protocol_backimage_proto_rawDescOnce sync.Once
	file_pkg_protocol_backimage_proto_rawDescData = file_pkg_protocol_backimage_proto_rawDesc
)

func file_pkg_protocol_backimage_proto_rawDescGZIP() []byte {
	file_pkg_protocol_backimage_proto_rawDescOnce.Do(func() {
		file_pkg_protocol_backimage_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_protocol_backimage_proto_rawDescData)
	})
	return file_pkg_protocol_backimage_proto_rawDescData
}

var file_pkg_protocol_backimage_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_protocol_backimage_proto_goTypes = []any{
	(*Hello)(nil),            // 0: backimage.v1.Hello
	(*HelloAck)(nil),         // 1: backimage.v1.HelloAck
	(*BackupStart)(nil),      // 2: backimage.v1.BackupStart
	(*Platform)(nil),         // 3: backimage.v1.Platform
	(*LayerStart)(nil),       // 4: backimage.v1.LayerStart
	(*LayerEnd)(nil),         // 5: backimage.v1.LayerEnd
	(*Token)(nil),            // 6: backimage.v1.Token
	(*TokenRequest)(nil),     // 7: backimage.v1.TokenRequest
	(*Progress)(nil),         // 8: backimage.v1.Progress
	(*BackupEnd)(nil),        // 9: backimage.v1.BackupEnd
	(*StreamStart)(nil),      // 10: backimage.v1.StreamStart
	(*ArchiveConfig)(nil),    // 11: backimage.v1.ArchiveConfig
	(*CDCParams)(nil),        // 12: backimage.v1.CDCParams
	(*HostInfo)(nil),         // 13: backimage.v1.HostInfo
	(*EncryptionConfig)(nil), // 14: backimage.v1.EncryptionConfig
	(*StreamAck)(nil),        // 15: backimage.v1.StreamAck
	(*StreamEnd)(nil),        // 16: backimage.v1.StreamEnd
	(*StreamProgress)(nil),   // 17: backimage.v1.StreamProgress
	(*Error)(nil),            // 18: backimage.v1.Error
	(*ClientMessage)(nil),    // 19: backimage.v1.ClientMessage
	(*ServerMessage)(nil),    // 20: backimage.v1.ServerMessage
	(*BackupAck)(nil),        // 21: backimage.v1.BackupAck
	(*LayerAck)(nil),         // 22: backimage.v1.LayerAck
	(*Cancel)(nil),           // 23: backimage.v1.Cancel
	nil,                      // 24: backimage.v1.EncryptionConfig.KeyFilesEntry
}
var file_pkg_protocol_backimage_proto_depIdxs = []int32{
	3,  // 0: backimage.v1.BackupStart.platforms:type_name -> backimage.v1.Platform
	11, // 1: backimage.v1.StreamStart.archive:type_name -> backimage.v1.ArchiveConfig
	14, // 2: backimage.v1.StreamStart.encryption:type_name -> backimage.v1.EncryptionConfig
	3,  // 3: backimage.v1.StreamStart.platforms:type_name -> backimage.v1.Platform
	13, // 4: backimage.v1.StreamStart.host:type_name -> backimage.v1.HostInfo
	12, // 5: backimage.v1.StreamStart.cdc:type_name -> backimage.v1.CDCParams
	24, // 6: backimage.v1.EncryptionConfig.key_files:type_name -> backimage.v1.EncryptionConfig.KeyFilesEntry
	7,  // 7: backimage.v1.StreamAck.token_request:type_name -> backimage.v1.TokenRequest
	0,  // 8: backimage.v1.ClientMessage.hello:type_name -> backimage.v1.Hello
	2,  // 9: backimage.v1.ClientMessage.backup_start:type_name -> backimage.v1.BackupStart
	4,  // 10: backimage.v1.ClientMessage.layer_start:type_name -> backimage.v1.LayerStart
	5,  // 11: backimage.v1.ClientMessage.layer_end:type_name -> backimage.v1.LayerEnd
	6,  // 12: backimage.v1.ClientMessage.token:type_name -> backimage.v1.Token
	18, // 13: backimage.v1.ClientMessage.error:type_name -> backimage.v1.Error
	23, // 14: backimage.v1.ClientMessage.cancel:type_name -> backimage.v1.Cancel
	10, // 15: backimage.v1.ClientMessage.stream_start:type_name -> backimage.v1.StreamStart
	16, // 16: backimage.v1.ClientMessage.stream_end:type_name -> backimage.v1.StreamEnd
	1,  // 17: backimage.v1.ServerMessage.hello_ack:type_name -> backimage.v1.HelloAck
	7,  // 18: backimage.v1.ServerMessage.token_request:type_name -> backimage.v1.TokenRequest
	8,  // 19: backimage.v1.ServerMessage.progress:type_name -> backimage.v1.Progress
	9,  // 20: backimage.v1.ServerMessage.backup_end:type_name -> backimage.v1.BackupEnd
	18, // 21: backimage.v1.ServerMessage.error:type_name -> backimage.v1.Error
	22, // 22: backimage.v1.ServerMessage.layer_ack:type_name -> backimage.v1.LayerAck
	21, // 23: backimage.v1.ServerMessage.backup_ack:type_name -> backimage.v1.BackupAck
	15, // 24: backimage.v1.ServerMessage.stream_ack:type_name -> backimage.v1.StreamAck
	17, // 25: backimage.v1.ServerMessage.stream_progress:type_name -> backimage.v1.StreamProgress
	7,  // 26: backimage.v1.BackupAck.token_request:type_name -> backimage.v1.TokenRequest
	27, // [27:27] is the sub-list for method output_type
	27, // [27:27] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_pkg_protocol_backimage_proto_init() }
func file_pkg_protocol_backimage_proto_init() {
	if File_pkg_protocol_backimage_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_protocol_backimage_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Hello); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*HelloAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*BackupStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*Platform); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*LayerStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*LayerEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*Token); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*TokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*Progress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*BackupEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*StreamStart); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[11].Exporter = func(v any, i int) any {
			switch v := v.(*ArchiveConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[12].Exporter = func(v any, i int) any {
			switch v := v.(*CDCParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[13].Exporter = func(v any, i int) any {
			switch v := v.(*HostInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[14].Exporter = func(v any, i int) any {
			switch v := v.(*EncryptionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[15].Exporter = func(v any, i int) any {
			switch v := v.(*StreamAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[16].Exporter = func(v any, i int) any {
			switch v := v.(*StreamEnd); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[17].Exporter = func(v any, i int) any {
			switch v := v.(*StreamProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[18].Exporter = func(v any, i int) any {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[19].Exporter = func(v any, i int) any {
			switch v := v.(*ClientMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[20].Exporter = func(v any, i int) any {
			switch v := v.(*ServerMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[21].Exporter = func(v any, i int) any {
			switch v := v.(*BackupAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[22].Exporter = func(v any, i int) any {
			switch v := v.(*LayerAck); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_protocol_backimage_proto_msgTypes[23].Exporter = func(v any, i int) any {
			switch v := v.(*Cancel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_pkg_protocol_backimage_proto_msgTypes[19].OneofWrappers = []any{
		(*ClientMessage_Hello)(nil),
		(*ClientMessage_BackupStart)(nil),
		(*ClientMessage_LayerStart)(nil),
		(*ClientMessage_LayerEnd)(nil),
		(*ClientMessage_Token)(nil),
		(*ClientMessage_Error)(nil),
		(*ClientMessage_Cancel)(nil),
		(*ClientMessage_StreamStart)(nil),
		(*ClientMessage_StreamEnd)(nil),
	}
	file_pkg_protocol_backimage_proto_msgTypes[20].OneofWrappers = []any{
		(*ServerMessage_HelloAck)(nil),
		(*ServerMessage_TokenRequest)(nil),
		(*ServerMessage_Progress)(nil),
		(*ServerMessage_BackupEnd)(nil),
		(*ServerMessage_Error)(nil),
		(*ServerMessage_LayerAck)(nil),
		(*ServerMessage_BackupAck)(nil),
		(*ServerMessage_StreamAck)(nil),
		(*ServerMessage_StreamProgress)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_protocol_backimage_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_protocol_backimage_proto_goTypes,
		DependencyIndexes: file_pkg_protocol_backimage_proto_depIdxs,
		MessageInfos:      file_pkg_protocol_backimage_proto_msgTypes,
	}.Build()
	File_pkg_protocol_backimage_proto = out.File
	file_pkg_protocol_backimage_proto_rawDesc = nil
	file_pkg_protocol_backimage_proto_goTypes = nil
	file_pkg_protocol_backimage_proto_depIdxs = nil
}
